### ISSUE TITLE
Sql error

### ISSUE THREAD

**Issue by karamatf** [RonRaj101/BarterMate#2]
Error
SQL query:

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `P_ID` int(11) NOT NULL,
  `P_NAME` text NOT NULL,
  `P_DESC` text NOT NULL,
  `P_CATEGORY` int(11) NOT NULL,
  `P_EXC_TYPE` int(11) NOT NULL,
  `P_MONETARY_VAL` int(11) DEFAULT NULL,
  `P_VIEWS` int(11) NOT NULL DEFAULT 0,
  `P_CREATE_DATE` text NOT NULL DEFAULT current_timestamp(),
  `P_BY_U_ID` int(11) NOT NULL,
  `P_FEATURED` int(11) NOT NULL DEFAULT 0,
  `P_STATUS` int(11) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
MySQL said: Documentation

#1067 - Invalid default value for 'P_CREATE_DATE'

Hi i keep getting this error i tried to change the value of P_create but the error keeps returning when uploading onto mysql ver 8 on cpanel

i did manage to put it on cyberpanel but there its refusing to connect to the database is there another location to change dbase

**Comment by RonRaj101** [comment]
No Unfortunately, this was a very rough database made for testing purposes. In theory it should just work with importing in mysql. Try changing the type, there might be a newer way to define timestamps in the latest mysql version

**Comment by RonRaj101** [comment]
Also sorry for the extremely late reply.
